spring:
  application:
    name: storemg
  datasource:
    url: jdbc:mysql://localhost:3306/storemg?createDatabaseIfNotExist=true
    username: root
    password: magaby2280@
stripe:
  apiUrl: https://api.stripe.com
  enable: true
  timeout: 1000
  supported-currencies: USD,EUR,GBP
payment-gateway: paypal
mail:
  host: https://smtp.gmail.com
  port: 5761